// movies_data.js

const moviesData = [
    {
        id: 'zootopia-2',
        title: 'Zootopia 2',
        poster: './images/cartoons/zootopia-2.png',
        description: '"Zootopia 2" (hay "Phi Vụ Động Trời 2") tiếp tục câu chuyện về cặp đôi cảnh sát Judy Hopps và Nick Wilde, khi họ cùng nhau điều tra một vụ án mới. Lần này, họ sẽ khám phá một khu đầm lầy bí ẩn và gặp gỡ những loài động vật mới lạ. Vụ án được mô tả là phức tạp và nguy hiểm nhất mà họ từng đối mặt. ',
        rating: 9.0, 
        duration: '130m',
        quality: '4K',
        age_restriction: '7+',
        genre: 'Phiêu lưu, Hoạt hình, Hài',
        releaseYear: 2025,
        director: 'Jared Bush, Byron Howard',
        actors: 'Ginnifer Goodwin, Jason Bateman, Ke Huy Quan',
        trailer: 'https://www.youtube.com/embed/xo4rkcC7kFc?si=c18xmCRDnCR2Xi1x&rel=0&modestbranding=1',
        type: "latest"
    },
    {
        id: 'stranger-5',
        title: 'Stranger Things: Season 5',
        poster: './images/series/stranger-things-5.png',
        description: 'Trong Stranger Things 5, thị trấn Hawkins rơi vào tình trạng phong tỏa sau khi các khe nứt kết nối với Thế Giới Ngược xuất hiện khắp nơi. Cả nhóm bạn phải tái hợp để đối đầu với Vecna trong trận chiến cuối cùng, trong khi Eleven bị truy đuổi, và Will bắt đầu cảm nhận rõ hơn mối liên kết bí ẩn với thế lực bóng tối. Đây là cuộc chiến quyết định số phận thế giới – và cả chính họ.',
        rating: 9.0,
        duration: '60m',          
        quality: '4K',
        age_restriction: '13+',
        genre: 'Khoa học viễn tưởng, Kinh dị, Bí ẩn, Tâm lý',
        releaseYear: 2025,
        director: 'Matt & Ross Duffer (showrunners), episodic directors',
        actors: 'Millie Bobby Brown, David Harbour, Winona Ryder',
        trailer: 'https://www.youtube.com/embed/QlYrNC_1Xmk?si=yLbaJMjAyC_OfmaW&rel=0&modestbranding=1',
        type: "latest"
    },
    {
        id: 'thunderbolt',
        title: 'Thunderbolts',
        poster: './images/movies/thunderbolts.png',
        description: 'Sau khi thấy mình bị mắc kẹt trong một cái bẫy chết người, một nhóm phản anh hùng phi thường phải thực hiện một nhiệm vụ nguy hiểm buộc họ phải đối mặt với những góc tối nhất trong quá khứ của mình.',
        rating: 7.7,   
        duration: '126m',
        quality: 'HD/4K',
        age_restriction: '13+',
        genre: 'Hành động, Phiêu lưu, Tội phạm, Chính kịch, Siêu anh hùng',
        releaseYear: 2025,
        director: 'Jake Schreier',
        actors: 'Florence Pugh, Sebastian Stan, David Harbour',
        trailer: 'https://www.youtube.com/embed/-sAOWhvheK8?si=n8a-DoKlXwITJL9S&rel=0&modestbranding=1',
        type: "latest"
    },
    {
        id: 'fantastic-4',
        title: 'Fantastic 4',
        poster: './images/movies/fantastic-4.png',
        description: 'Sau một chuyến bay thám hiểm vũ trụ, bốn phi hành gia bất ngờ sở hữu năng lực siêu nhiên và trở thành gia đình siêu anh hùng đầu tiên của Marvel. The Fantastic Four: First Steps là bộ phim mở đầu Kỷ nguyên anh hùng thứ sáu (Phase Six), đặt nền móng cho siêu bom tấn Avengers: Doomsday trong năm sau.',
        rating: 7.8,
        duration: '126m',    
        quality: '4K',
        age_restriction: '13+',
        genre: 'Hành động, Phiêu lưu, Khoa học viễn tưởng, Siêu anh hùng',
        releaseYear: 2025,
        director: 'Matt Shakman',
        actors: 'Pedro Pascal, Vanessa Kirby, Joseph Quinn',
        trailer: 'https://www.youtube.com/embed/pAsmrKyMqaA?si=9_fFBqbIjCBxX_Pq&rel=0&modestbranding=1',
        type: "latest"
    },
    {
        id: 'mission-impossible-8',
        title: 'Mission: Impossible 8',
        poster: './images/movies/mission-impossible.png',
        description: '"Nhiệm vụ bất khả thi 8" (Mission: Impossible 8) tiếp tục câu chuyện từ phần trước, khi thế giới đối mặt với mối đe dọa từ trí tuệ nhân tạo "The Entity". Ethan Hunt và đội IMF phải tìm hai nửa của chìa khóa kỹ thuật số để ngăn chặn "The Entity" thao túng thế giới. Cuộc hành trình đưa họ đi khắp nơi, từ những bí mật đen tối đến các căn cứ quân sự, đối mặt với những lựa chọn khó khăn và hiểm họa công nghệ. ',
        rating: 7.4,  
        duration: '169m',
        quality: 'HD/4K',
        age_restriction: '13+',
        genre: 'Hành động, Phiêu lưu, Gián điệp',
        releaseYear: 2025,
        director: 'Christopher McQuarrie',
        actors: 'Tom Cruise, Simon Pegg, Ving Rhames',
        trailer: 'https://www.youtube.com/embed/fsQgc9pCyDU?si=xUAfcg6GDnzQ_v0x&rel=0&modestbranding=1',
        type: "latest"
    },
    
    {
        id: 'Alice',
        title: 'Alice in Borderland: Season 2',
        poster: './images/series/alice-in-borderland.jpg',
        description: 'Arisu - một thanh niên chán nản, thất nghiệp và bị ám ảnh bởi trò chơi điện tử. Đột nhiên thấy mình ở một phiên bản Tokyo xa lạ, trống rỗng, nơi anh và bạn bè phải tham gia vào những trò chơi nguy hiểm để sinh tồn.',
        rating: 8.5,
        duration: '60m',
        quality: 'HD/4K',
        age_restriction: '17+',
        genre: 'Khoa học viễn tưởng, Drama, Giật gân',
        releaseYear: 2022,
        director: 'Shinsuke Sato',
        actors: 'Kento Yamazaki, Tao Tsuchiya, Nijirō Murakami',
        trailer: 'https://www.youtube.com/embed/1ifgEQCevYc?si=pW-rhMiTGcFJZATN&rel=0&modestbranding=1',
        type: "latest"
    },
    {
        id: 'minecraft',
        title: 'A Minecraft Movie',
        poster: './images/movies/minecraft.png',
        description: 'Bốn kẻ lập dị bất ngờ bị cuốn qua một cánh cổng bí ẩn vào một xứ sở hình khối kỳ lạ, nơi trí tưởng tượng là sức mạnh cốt lõi. Để quay trở về nhà, họ phải chinh phục thế giới này bằng cách tham gia vào một cuộc hành trình cùng với một người thợ thủ công tài ba ngoài mong đợi.',
        rating: 8.0,
        duration: '101m',
        quality: 'HD/4K',
        age_restriction: '7+',
        genre: 'Giả tưởng, Phiêu lưu, Hài, Hành động',
        releaseYear: 2025,
        director: 'Jared Hess',
        actors: 'Jack Black, Jason Momoa, Danielle Brooks',
        trailer: 'https://www.youtube.com/embed/wJO_vIDZn-I?si=GbP-sFtTVENqvIQc&rel=0&modestbranding=1',
        type: "latest"
    },
    

    // hiện đang thịnh hành
    {
        id: 'shogun',
        title: 'Shogun',
        poster: './images/movies/shogun.png',
        description: 'Khi một con tàu bí ẩn của châu Âu được tìm thấy mắc kẹt ở một làng chài Nhật Bản gần đó, Chúa tể Yoshii Toranaga phát hiện ra những bí mật có thể làm thay đổi cán cân quyền lực và tàn phá kẻ thù của mình.',
        rating: 9.0,
        duration: '60m',
        quality: 'HD/4K',
        age_restriction: '16+',
        genre: 'Lịch sử, Phiêu lưu, Chiến tranh, Chính trị',
        releaseYear: 2024,
        director: 'Justin Marks, Rachel Kondo, episodic directors like Frederick E.O.Toye',
        actors: 'Hiroyuki Sanada, Anna Sawai, Cosmo Jarvis',
        trailer: 'https://www.youtube.com/embed/HIs9x49DK7I?si=fFJwe9KHpb5Cmmsz&rel=0&modestbranding=1',
        type: "trending",
    },
    {
        id: 'the-glory',
        title: 'The Glory',
        poster: './images/series/the-glory.png',
        description: 'Nhiều năm sau khi thoát khỏi cảnh bạo lực kinh hoàng ở trường cấp ba, một phụ nữ tiến hành âm mưu trả thù đầy tinh vi để khiến các thủ phạm phải trả giá cho tội ác của mình.',
        rating: 8.9,
        duration: '60m',
        quality: 'HD/4K',
        age_restriction: '16+',
        genre: 'Tâm lý, Bí ẩn, Giật gân, Báo thù',
        releaseYear: 2022,
        director: 'Ahn Gil-ho',
        actors: 'Song Hye-kyo, Lee Do-hyun, Lim Ji-yeon',
        trailer: 'https://www.youtube.com/embed/rvJP7sAhXk4?si=tLwjOetzJgomz9FS&rel=0&modestbranding=1',
        type: "trending",
    },
    {
        id: 'infinity-war',
        title: 'Avengers: Infinity War',
        poster: './images/movies/avengers-infinity-war.png',
        description: 'Các Avengers và các đồng minh của họ phải sẵn sàng hy sinh tất cả để cố gắng đánh bại Thanos hùng mạnh trước khi cuộc tàn phá và hủy diệt của hắn chấm dứt toàn bộ vũ trụ.',
        rating: 8.9,
        duration: '149m',
        quality: 'HD/4K',
        age_restriction: '13+',
        genre: 'Hành động, Phiêu lưu, Khoa học viễn tưởng, Siêu anh hùng',
        releaseYear: 2018,
        director: 'Anthony Russo, Joe Russo',
        actors: 'Robert Downey Jr., Chris Evans, Chris Hemsworth',
        trailer: 'https://www.youtube.com/embed/6ZfuNTqbHE8?si=Nx5CoDfPLOEHAgC2&rel=0&modestbranding=1',
        type: "trending",
    },
    {
        id: 'stranger-t-1',
        title: 'Stranger Things: Season 1',
        poster: './images/series/stranger-things.png',
        description: 'Trên đường về nhà từ nhà một người bạn, cậu bé Will nhìn thấy một điều gì đó đáng sợ. Gần đó, một bí mật đen tối ẩn núp trong sâu thẳm của một phòng thí nghiệm của chính phủ',
        rating: 8.8,
        duration: '60m',
        quality: 'HD/4K',
        age_restriction: '13+',
        genre: 'Khoa học viễn tưởng, Kinh dị, Bí ẩn, Chính kịch',
        releaseYear: 2016,
        director: 'Duffer Brothers (Matt & Ross), Shawn Levy',
        actors: 'Winona Ryder, David Harbour, Millie Bobby Brown',
        trailer: 'https://www.youtube.com/embed/mnd7sFt5c3A?si=abmOxhhCcb2AwIGK&rel=0&modestbranding=1',
        type: "trending",
    },
    {
        id: 'peaky-blinders-1',
        title: 'Peaky Blinders: Season 1',
        poster: './images/series/peaky-blinders.png',
        description: 'Peaky Blinders phần 1 nói về gia đình Shelby, những người cầm đầu băng đảng Peaky Blinders khét tiếng trong thế giới ngầm với bộ não là Tommy Shelby, đứa con trai thứ hai. Bộ phim là hành trình thăng tiến trong thế giới ngầm của Tommy bằng những mưu mô, thủ đoạn tàn nhẫn',
        rating: 8.6,
        duration: '60m',
        quality: 'HD',
        age_restriction: '17+',
        genre: 'Chính kịch lịch sử, Tội phạm',
        releaseYear: 2013,
        director: 'Otto Bathurst, Tom Harper',
        actors: 'Cillian Murphy, Helen McCrory, Paul Anderson',
        trailer: 'https://www.youtube.com/embed/oVzVdvGIC7U?si=mBDyHLITQ0UMg4Aa&rel=0&modestbranding=1',
        type: "trending",
    },
    {
        id: 'civil-war',
        title: 'Captain America: Civil War',
        poster: './images/movies/civil-war.png',
        description: 'Sự can dự chính trị vào công việc của Avengers gây ra rạn nứt giữa Captain America và Iron Man.Khi Captain America và Iron Man có quan điểm đối lập, nhóm Avengers đã chọn phe, dẫn đến trận chiến cuối cùng giữa những siêu anh hùng mạnh nhất Trái Đất.',
        rating: 8.5,
        duration: '147m',
        quality: 'HD/4K',
        age_restriction: '13+',
        genre: 'Hành động, Phiêu lưu, Khoa học viễn tưởng, Siêu anh hùng',
        releaseYear: 2016,
        director: 'Anthony Russo, Joe Russo',
        actors: 'Chris Evans, Robert Downey Jr., Scarlett Johansson',
        trailer: 'https://www.youtube.com/embed/dKrVegVI0Us?si=_R1RK8WvsUk7scrL&rel=0&modestbranding=1',
        type: "trending",
    },
    {
        id: 'suicide-squad',
        title: 'Suicide Squad 2',
        poster: './images/movies/suicide-squad.png',
        description: 'Những siêu ác nhân Harley Quinn, Bloodsport, Peacemaker và một nhóm tội phạm lập dị tại nhà tù Belle Reve đã gia nhập Lực lượng đặc nhiệm X siêu bí mật và siêu mờ ám khi họ bị thả xuống hòn đảo Corto Maltese xa xôi, đầy rẫy kẻ thù.',
        rating: 7.9,
        duration: '132m',
        quality: 'HD/4K',
        age_restriction: '17+',
        genre: 'Hành động, Phiêu lưu, Siêu anh hùng, Hài đen',
        releaseYear: 2021,
        director: 'James Gunn',
        actors: 'Margot Robbie, Idris Elba, John Cena',
        trailer: 'https://www.youtube.com/embed/eg5ciqQzmK0?si=AJerNYyplT3lnebz&rel=0&modestbranding=1',
        type: "trending",
    },


    // phim điện ảnh ------------------------------------------------------------------------------
    {
        id: 'brave-new-world',
        title: 'Captain America: Brave New World',
        poster: './images/movies/captain.png',
        description: 'Sau khi gặp Tổng thống Hoa Kỳ mới đắc cử Thaddeus Ross, Sam phải đối mặt với một sự cố quy mô quốc tế. Anh phải tìm ra ra mục đích đằng sau trước khi kẻ chủ mưu thực sự khiến cả thế giới phải khiếp sợ.',
        rating: 7.8,
        duration: '118m',
        quality: 'HD/4K',
        age_restriction: '13+',
        genre: 'Hành động, Phiêu lưu, Siêu anh hùng',
        releaseYear: 2025,
        director: 'Julius Onah',
        actors: 'Anthony Mackie, Harrison Ford, Giancarlo Esposito',
        trailer: 'https://www.youtube.com/embed/1pHDWnXmK7Y?si=cOWbUNEl733yeoiK&rel=0&modestbranding=1',
        type: "movies",
    },
    {
        id: 'the-dark-knight',
        title: 'The Dark Knight',
        poster: './images/movies/bat-man.jpg',
        description: 'Khi mối đe dọa mang tên Joker gây ra sự tàn phá và hỗn loạn cho người dân Gotham, Batman, James Gordon và Harvey Dent phải hợp tác để chấm dứt sự điên rồ này.',
        rating: 9.0,
        duration: '152m',
        quality: 'HD/4K',
        age_restriction: '13+',
        genre: 'Hành động, Phiêu lưu, Chính kịch, Tội phạm, Siêu anh hùng',
        releaseYear: 2008,
        director: 'Christopher Nolan',
        actors: 'Christian Bale, Heath Ledger, Aaron Eckhart',
        trailer: 'https://www.youtube.com/embed/EXeTwQWrcwY?si=J_ZBWowAicvJqxne&rel=0&modestbranding=1',
        type: "movies",
    },
    {
        id: 'call',
        title: 'The Call',
        poster: './images/movies/call.jpg',
        description: 'Hai người sống ở hai thời đại khác nhau. Seo-Yeon sống ở hiện tại và Young-Sook sống ở quá khứ. Một cuộc gọi điện thoại kết nối hai người, và cuộc sống của họ thay đổi không thể cứu vãn.',
        rating: 7.1,      
        duration: '112m',        
        quality: 'HD/4K',
        age_restriction: '16+',
        genre: 'Bí ẩn, Giật gân, Tâm lý, Khoa học viễn tưởng',
        releaseYear: 2020,
        director: 'Lee Chung-hyun',
        actors: 'Park Shin-hye, Jeon Jong-seo, Kim Sung-ryung',
        trailer: 'https://www.youtube.com/embed/hxkKeniT-0Q?si=jobFJBD4EaOYPUFg&rel=0&modestbranding=1',
        type: "movies",
    },
    {
        id: 'black-adam',
        title: 'Black Adam',
        poster: './images/movies/black-adam.png',
        description: 'Thức tỉnh sau 5000 năm, Black Adam trở thành người bảo vệ tàn nhẫn của thế giới: một phản diện để đối đầu với những kẻ như Superman và Wonder Woman. Giờ đây, ở thế kỷ 21, Black Adam phải đối đầu với Justice Society of America và các anh hùng của nó: Doctor Fate, Hawkman, Atom Smasher và Cyclone. Số phận của thế giới đang bị đe dọa.',
        rating: 8.0,
        duration: '125m',
        quality: 'HD/4K',
        age_restriction: '13+',
        genre: 'Hành động, Phiêu lưu, Siêu anh hùng, Fantasy',
        releaseYear: 2022,
        director: 'Jaume Collet-Serra',
        actors: 'Dwayne Johnson, Aldis Hodge, Pierce Brosnan',
        trailer: 'https://www.youtube.com/embed/mkomfZHG5q4?si=KmAsPprn7BUBmcC2&rel=0&modestbranding=1',
        type: "movies",
    },
    {
        id: 'deadpool-wolverine',
        title: 'Deadpool and Wolverine',
        poster: './images/movies/wolverine.png',
        description: 'Cuộc sống yên bình của Deadpool bị đảo lộn khi Cơ quan Quản lý Dòng thời gian (Time Variance Authority) chiêu mộ anh để giúp bảo vệ đa vũ trụ. Không lâu sau, anh hợp lực với người bạn tương lai của mình, Wolverine, để hoàn thành nhiệm vụ và cứu thế giới khỏi một mối đe dọa tồn vong.',
        rating: 8.5,
        duration: '128m',
        quality: 'HD/4K',
        age_restriction: '17+',
        genre: 'Hành động, Phiêu lưu, Hài, Siêu anh hùng',
        releaseYear: 2024,
        director: 'Shawn Levy',
        actors: 'Ryan Reynolds, Hugh Jackman, Emma Corrin',
        trailer: 'https://www.youtube.com/embed/73_1biulkYk?si=bTKQHReivRlnHKsr&rel=0&modestbranding=1',
        type: "movies",
    },
    {
        id: 'extraction-2',
        title: 'Extraction',
        poster: './images/movies/extraction.png',
        description: 'Tyler Rake, một lính đánh thuê chợ đen không biết sợ hãi, bắt đầu cuộc hành trình nguy hiểm nhất trong sự nghiệp của mình khi anh được giao nhiệm vụ giải cứu đứa con trai bị bắt cóc của một trùm tội phạm quốc tế đang bị giam cầm.',
        rating: 8.0,
        duration: '117m',
        quality: 'HD/4K',
        age_restriction: '18+',
        genre: 'Hành động, Giật gân',
        releaseYear: 2020,
        director: 'Sam Hargrave',
        actors: 'Chris Hemsworth, Rudhraksh Jaiswal, Randeep Hooda',
        trailer: 'https://www.youtube.com/embed/L6P3nI6VnlY?si=IgbFCTGGwye1ylpm&rel=0&modestbranding=1',
        type: "movies",
    },
    {
        id: 'no-way-home',
        title: 'Spider Man: No Way Home',
        poster: './images/movies/spider.png',
        description: 'Với danh tính của Người Nhện giờ đã được tiết lộ, Peter đã nhờ đến sự giúp đỡ của Doctor Strange. Khi một câu thần chú sai, những kẻ thù nguy hiểm từ các thế giới khác bắt đầu xuất hiện, buộc Peter phải khám phá ra ý nghĩa thực sự của việc trở thành Người Nhện.',
        rating: 8.5,
        duration: '148m',
        quality: 'HD/4K',
        age_restriction: '13+',
        genre: 'Hành động, Phiêu lưu, Khoa học viễn tưởng, Siêu anh hùng',
        releaseYear: 2021,
        director: 'Jon Watts',
        actors: 'Tom Holland, Zendaya, Benedict Cumberbatch',
        trailer: 'https://www.youtube.com/embed/JfVOs4VSpmA?si=otIaP8F-HJv84Ntx&rel=0&modestbranding=1',
        type: "movies",
    },    
    {
        id: 'fight-club',
        title: 'Fight Club',
        poster: './images/movies/fight-club.png',
        description: 'Một người đàn ông chán nản (Edward Norton) mắc chứng mất ngủ gặp một người bán xà phòng kỳ lạ tên là Tyler Durden (Brad Pitt) và sớm thấy mình đang sống trong ngôi nhà tồi tàn của anh ta sau khi căn hộ hoàn hảo của anh ta bị phá hủy. Hai người đàn ông buồn chán thành lập một câu lạc bộ ngầm với những quy tắc nghiêm ngặt và chiến đấu với những người đàn ông khác đang chán ngán cuộc sống tầm thường của họ. Mối quan hệ hoàn hảo của họ trở nên rạn nứt khi Marla (Helena Bonham Carter), một người bạn cùng nhóm hỗ trợ, thu hút sự chú ý của Tyler.',
        rating: 8.8, 
        duration: '139m',
        quality: 'HD/4K',
        age_restriction: '18+',
        genre: 'Chính kịch, Giật gân, Hài đen',
        releaseYear: 1999,
        director: 'David Fincher',
        actors: 'Edward Norton, Brad Pitt, Helena Bonham Carter',
        trailer: 'https://www.youtube.com/embed/qtRKdVHc-cE?si=Ymu5Q8OoCnB9M8fI&rel=0&modestbranding=1',
        type: "movies"
    },
    {
        id: 'kong-vs-godzilla',
        title: 'Godzilla vs Kong',
        poster: './images/movies/kong-vs-godzilla.png',
        description: 'Chương tiếp theo hoành tráng trong vũ trụ điện ảnh Monsterverse sẽ đưa hai biểu tượng vĩ đại nhất trong lịch sử điện ảnh đối đầu với nhau - Godzilla đáng sợ và Kong hùng mạnh - với nhân loại bị kẹt trong thế cân bằng.',
        rating: 7.8,
        duration: '113m',
        quality: 'HD/4K',
        age_restriction: '13+',
        genre: 'Hành động, Phiêu lưu, Khoa học viễn tưởng',
        releaseYear: 2021,
        director: 'Adam Wingard',
        actors: 'Alexander Skarsgård, Millie Bobby Brown, Rebecca Hall',
        trailer: 'https://www.youtube.com/embed/odM92ap8_c0?si=6_C3uwx49_YpJ1p9&rel=0&modestbranding=1',
        type: "movies"
    },
    {
        id: 'end-game',
        title: 'Avengers: End Game',
        poster: './images/movies/end-game.jpg',
        description: 'Sau những sự kiện tàn khốc của Avengers: Cuộc Chiến Vô Cực (2018) , vũ trụ đã bị hủy hoại. Với sự giúp đỡ của những đồng minh còn lại, Avengers một lần nữa tập hợp lại để đảo ngược hành động của Thanos và khôi phục lại sự cân bằng cho vũ trụ.',
        rating: 9.0,
        duration: '181m',
        quality: 'HD/4K',
        age_restriction: '13+',
        genre: 'Hành động, Phiêu lưu, Khoa học viễn tưởng, Siêu anh hùng',
        releaseYear: 2019,
        director: 'Anthony Russo, Joe Russo',
        actors: 'Robert Downey Jr., Chris Evans, Mark Ruffalo',
        trailer: 'https://www.youtube.com/embed/TcMBFSGVi1c?si=8fh27R2x7HNyk3pc&rel=0&modestbranding=1',
        type: "movies"
    },


    // series phim ------------------------------------------------------------------------------
    {
        id: 'breaking-bad',
        title: 'Breaking Bad',
        poster: './images/series/breaking-bad.png',
        description: 'Sau khi được chẩn đoán mắc ung thư phổi giai đoạn cuối, một giáo viên hóa học trung học đang gặp khó khăn đưa ra một quyết định táo bạo để đảm bảo tương lai cho gia đình mình — bước vào thế giới buôn bán ma túy cùng một học sinh cũ.',
        rating: 9.0,
        duration: '60m',
        quality: 'HD',
        age_restriction: '17+',
        genre: 'Tội phạm, Chính kịch, Hồi hộp',
        releaseYear: 2008,
        director: 'Vince Gilligan, Adam Bernstein, Jim McKay',
        actors: 'Bryan Cranston, Aaron Paul, Anna Gunn',
        trailer: 'https://www.youtube.com/embed/HhesaQXLuRY?si=1kPY_Ay7ZBAIYHxi&rel=0&modestbranding=1',
        type: "series",
    },
    {
        id: 'the-boys-1',
        title: 'The Boys',
        poster: './images/series/the-boys.png',
        description: 'Khi một siêu anh hùng giết chết tình yêu của đời mình, nhân viên bán hàng Hughie Campbell đã hợp tác với Billy Butcher, một chiến binh quyết tâm trừng phạt những siêu anh hùng đồi bại và cuộc sống của Hughie sẽ không bao giờ còn như cũ nữa.',
        rating: 8.5,
        duration: '60m',
        quality: 'HD/4K',
        age_restriction: '17+',
        genre: 'Drama, Hành động, Phiêu lưu, Kinh dị, Giật gân',
        releaseYear: 2014,
        director: 'Scott M. Gimple (showrunner), Greg Nicotero, Ernest Dickerson, Michael Satrazemis',
        actors: 'Andrew Lincoln, Norman Reedus, Steven Yeun',
        trailer: 'https://www.youtube.com/embed/tcrNsIaQkb4?si=2TwlB1o0vVjtffD9&rel=0&modestbranding=1',
        type: "series",
    },
    {
        id: 'the-walking-dead-5',
        title: 'The Walking Dead',
        poster: './images/series/the-walking-dead.png',
        description: 'Rick và nhóm của anh, cùng với Kingdom và Hilltop, cùng nhau chiến đấu chống lại Negan và Saviors.',
        rating: 7.8,
        duration: '60m',
        quality: 'HD',
        age_restriction: '13+',
        genre: 'Khoa học viễn tưởng, Phiêu lưu',
        releaseYear: 2009,
        director: 'James Cameron',
        actors: 'Sam Worthington, Zoe Saldana, Sigourney Weaver',
        trailer: 'https://www.youtube.com/embed/B__2hnNQlEQ?si=yvveTA8oDMRnQdoj&rel=0&modestbranding=1',
        type: "series",
    },
    {
        id: 'saul',
        title: 'Better Call Saul',
        poster: './images/series/better-call-saul.jpg',
        description: 'Những thử thách và đau khổ của luật sư hình sự Jimmy McGill trong những năm dẫn đến cuộc chạm trán định mệnh của anh với Walter White và Jesse Pinkman.',
        rating: 8.5,
        duration: '60m',
        quality: 'HD',
        age_restriction: '17+',
        genre: 'Chính kịch, Tội phạm, Drama, Hài châm biếm',
        releaseYear: 2015,
        director: 'Vince Gilligan, Michelle MacLaren, Adam Bernstein, Peter Gould',
        actors: 'Bob Odenkirk, Jonathan Banks, Rhea Seehorn',
        trailer: 'https://www.youtube.com/embed/HN4oydykJFc?si=OCaZTfhocCAW4-6u&rel=0&modestbranding=1',
        type: "series",
    },
    {
        id: 'shameless-1',
        title: 'Shameless: Season 1',
        poster: './images/series/shameless.png',
        description: 'Khi chúng ta gặp lại gia đình Gallagher, cuộc sống tại nhà bị đảo lộn bởi sự xuất hiện trở lại của Frank. Với Lip đã vào đại học và Ian vẫn mất tích, Fiona cố gắng kết nối với Debbie và Carl.',
        rating: 9.0,
        duration: '60m',
        quality: 'HD',
        age_restriction: '18+',
        genre: 'Hài - Chính kịch, Tội phạm, Gia đình, Châm biếm',
        releaseYear: 2011,
        director: 'Paul Abbott, John Wells, Mark Mylod, Otto Bathurst',
        actors: 'William H. Macy, Emmy Rossum, Joan Cusack',
        trailer: 'https://www.youtube.com/embed/9tvkYS5cA58?si=SzbnI8GHAL3os-u0&rel=0&modestbranding=1',
        type: "series"
    },
    {
        id: 'the-last-of-us',
        title: 'The Last of Us',
        poster: './images/series/the-last-of-us.png',
        description: 'Năm 2003, một loại nấm ký sinh đã tàn phá hành tinh, biến con người thành những sinh vật hung dữ được gọi là Infected. Hai mươi năm sau, Joel - một người sống sót dày dạn kinh nghiệm, được thuê để đưa lậu Ellie 14 tuổi đến với nhóm Fireflies nổi loạn.',
        rating: 9.0,
        duration: '60m',
        quality: 'HD/4K',
        age_restriction: '17+',
        genre: 'Hành động, Chính kịch, Phiêu lưu, Kinh dị, Khoa học viễn tưởng',
        releaseYear: 2023,
        director: 'Craig Mazin, Neil Druckmann (showrunners); các đạo diễn episodic như Jasmila Žbanić, Ali Abbasi…',
        actors: 'Pedro Pascal, Bella Ramsey, Gabriel Luna',
        trailer: 'https://www.youtube.com/embed/TdcXP-groXc?si=-sD3KHNPZSBYnJmP&rel=0&modestbranding=1',
        type: "series",
    },
    {
        id: 'alice-1',
        title: 'Alice in Borderland',
        poster: './images/series/alice-in-borderland-1.png',
        description: 'Arisu - một thanh niên chán nản, thất nghiệp và bị ám ảnh bởi trò chơi điện tử. Đột nhiên thấy mình ở một phiên bản Tokyo xa lạ, trống rỗng, nơi anh và bạn bè phải tham gia vào những trò chơi nguy hiểm để sinh tồn.',
        rating: 9.0,
        duration: '60m',
        quality: 'HD/4K',
        age_restriction: '14+',
        genre: 'Khoa học viễn tưởng, Giật gân, Chính kịch',
        releaseYear: 2020,
        director: 'Shinsuke Sato',
        actors: 'Kento Yamazaki, Tao Tsuchiya, Nijirō Murakami',
        trailer: 'https://www.youtube.com/embed/49_44FFKZ1M?si=jZWvX-R5sB1V5Tav&rel=0&modestbranding=1',
        type: "series"
    },
    {
        id: 'stranger-2',
        title: 'Stranger Things: Season 2',
        poster: './images/series/stranger-things-2.jpg',
        description: 'Tiếp tục câu chuyện vào năm 1984, một năm sau các sự kiện xảy ra trong phần đầu tiên. Thị trấn Hawkins đang cố gắng hồi phục sau những sự kiện kỳ lạ liên quan đến việc mất tích của Will Byers và sự xuất hiện của cậu bé Eleven.',
        rating: 9.0,
        duration: '60m',
        quality: 'HD/4K',
        age_restriction: '13+',
        genre: 'Khoa học viễn tưởng, Kinh dị, Bí ẩn, Giả tưởng, Chính kịch',
        releaseYear: 2017,
        director: 'Matt & Ross Duffer, Shawn Levy',
        actors: 'Winona Ryder, David Harbour, Millie Bobby Brown',
        trailer: 'https://www.youtube.com/embed/R1ZXOOLMJ8s?si=Sqh9QovfMctFylKo&rel=0&modestbranding=1',
        type: "series"
    },
    {
        id: 'invinsible-1',
        title: 'Invinsible: Season 1',
        poster: './images/series/invinsible-1.png',
        description: 'Câu chuyện xoay quanh Mark Grayson, một cậu thiếu niên 17 tuổi giống như bao người khác cùng trang lứa — ngoại trừ việc cha của cậu là Omni-Man, siêu anh hùng mạnh nhất hành tinh. Nhưng khi Mark bắt đầu phát triển sức mạnh của riêng mình, cậu phát hiện ra rằng di sản của cha mình có thể không hề anh hùng như vẻ bề ngoài.',
        rating: 7.8,
        duration: '60m',
        quality: 'HD/4K',
        age_restriction: '17+',
        genre: 'Hoạt hình, Hành động, Phiêu anh hùng, Chính kịch, Khoa học viễn tưởng',
        releaseYear: 2021,
        director: 'Robert Valley (ep1), Robert Kirkman (creator/showrunner)',
        actors: 'Steven Yeun, Sandra Oh, J.K. Simmons, Gillian Jacobs',
        trailer: 'https://www.youtube.com/embed/-bfAVpuko5o?si=sdJDOiEuVN5lSFvf&rel=0&modestbranding=1',
        type: "series",
    },


    // phim hoạt hình  ------------------------------------------------------------------------------
    {
        id: 'invinsible-3',
        title: 'Invinsible: Season 3',
        poster: './images/cartoons/invinsible.png',
        description: 'Mọi thứ thay đổi khi Mark buộc phải đối mặt với quá khứ và tương lai của mình, đồng thời khám phá ra anh cần phải tiến xa đến mức nào để bảo vệ những người anh yêu thương.',
        rating: 8.5,
        duration: '60m',
        quality: 'HD/4K',
        age_restriction: '17+',
        genre: 'Hoạt hình, Hành động, Siêu anh hùng, Chính kịch, Bạo lực',
        releaseYear: 2025,
        director: 'Robert Kirkman (showrunner), Simon Racioppa, Haylee Herrick',
        actors: 'Steven Yeun, J.K. Simmons, Sandra Oh, Walton Goggins, Gillian Jacobs',
        trailer: 'https://www.youtube.com/embed/rbHUhCcSXEM?si=RxW8Sh2SlPEFSnze&rel=0&modestbranding=1',
        type: "cartoons",
    },
    {
        id: 'conan-27',
        title: 'Conan',
        poster: './images/cartoons/conan.png',
        description: 'Khi nhận được thông báo từ Kaito Kid về việc nhắm đến thanh kiếm Nhật của Toshizō Hijikata, Conan và nhóm phải nhanh chóng can thiệp để ngăn chặn kẻ trộm tài ba này. Trong khi Kid đang theo đuổi Big Jewel, lí do anh ta muốn chiếm đoạt thanh kiếm là một bí ẩn.',
        rating: 8.5,
        duration: '110m',
        quality: 'HD/4K',
        age_restriction: '13+',
        genre: 'Hoạt hình, Bí ẩn, Hành động, Phiêu lưu',
        releaseYear: 2024,
        director: 'Chika Nagaoka',
        actors: 'Minami Takayama, Kappei Yamaguchi, Wakana Yamazaki, Rikiya Koyama, Megumi Hayashibara',
        trailer: 'https://www.youtube.com/embed/C4pG3GbhQZw?si=nkFuRPAHmTiNWDjs&rel=0&modestbranding=1',
        type: "cartoons",
    },
    {
        id: 'minion-1',
        title: 'Minions',
        poster: './images/cartoons/monion.png',
        description: 'Những chú minion Stuart, Kevin và Bob được Scarlet Overkill, một siêu ác nhân, chiêu mộ. Cô cùng với người chồng là nhà phát minh Herb, lập nên một âm mưu thống trị thế giới.',
        rating: 8.0,
        duration: '91m',
        quality: 'HD',
        age_restriction: '7+',
        genre: 'Hoạt hình, Hài, Phiêu lưu, Gia đình',
        releaseYear: 2015,
        director: 'Kyle Balda, Pierre Coffin',
        actors: 'Sandra Bullock, Jon Hamm, Michael Keaton, Pierre Coffin',
        trailer: 'https://www.youtube.com/embed/eisKxhjBnZ0?si=bMJHIoVeApvNyJ6b&rel=0&modestbranding=1',
        type: "cartoons",
    },
    {
        id: 'zootopia',
        title: 'Zootopia',
        poster: './images/cartoons/zootopia.png',
        description: 'Thành phố Zootopia là một nơi nhiều loài động vật sinh sống và phát triển. Khi Judy Hopps trở thành chú thỏ đầu tiên gia nhập lực lượng cảnh sát, cô nhanh chóng nhận ra việc thực thi luật pháp khó khăn như thế nào. Quyết tâm chứng minh bản thân, Judy nắm bắt cơ hội để giải quyết một vụ án bí ẩn. Thật không may, điều đó có nghĩa là phải làm việc với Nick Wilde, một con cáo gian xảo khiến công việc của cô trở nên khó khăn hơn',
        rating: 8.0,
        duration: '108m',
        quality: 'HD/4K',
        age_restriction: '7+',
        genre: 'Hoạt hình, Hài, Phiêu lưu, Gia đình, Hành động',
        releaseYear: 2016,
        director: 'Byron Howard, Rich Moore',
        actors: 'Ginnifer Goodwin, Jason Bateman, Idris Elba, Jenny Slate',
        trailer: 'https://www.youtube.com/embed/jWM0ct-OLsM?si=fp5sMgJRqo_sc03l&rel=0&modestbranding=1',
        type: "cartoons",
    },
    {
        id: 'your-name',
        title: 'Your Name',
        poster: './images/cartoons/your-name.jpg',
        description: 'Mitsuha và Taki là hai người hoàn toàn xa lạ sống những cuộc sống hoàn toàn khác biệt. Nhưng khi Mitsuha muốn rời khỏi thị trấn miền núi của mình để đến thành phố Tokyo nhộn nhịp, họ lại trở nên gắn kết theo một cách kỳ lạ. Cô mơ thấy mình là một chàng trai sống ở Tokyo trong khi Taki mơ thấy mình là một cô gái đến từ một thị trấn nông thôn mà anh chưa từng đến.',
        rating: 9.0,
        duration: '106m',
        quality: 'HD',
        age_restriction: '13+',
        genre: 'Hoạt hình, Lãng mạn, Giả tưởng, Chính kịch',
        releaseYear: 2016,
        director: 'Makoto Shinkai',
        actors: 'Ryunosuke Kamiki, Mone Kamishiraishi, Ryo Narita, Aoi Yuki',
        trailer: 'https://www.youtube.com/embed/s0wTdCQoc2k?si=hvup6Rbo9EAEoNyj&rel=0&modestbranding=1',
        type: "cartoons",
    },
    {
        id: 'coco',
        title: 'Coco',
        poster: './images/cartoons/coco.jpg',
        description: 'Miguel, một cậu bé đam mê âm nhạc mặc dù gia đình đã cấm âm nhạc qua nhiều thế hệ, vô tình lạc vào Vùng Đất Của Người Chết để tìm hiểu bí mật về quá khứ gia đình. Cùng với Hector, cậu bước vào hành trình khám phá sự thật và theo đuổi ước mơ trở thành nhạc sĩ.',
        rating: 8.5,
        duration: '105m',
        quality: 'HD/4K',
        age_restriction: '7+',
        genre: 'Hoạt hình, Phiêu lưu, Gia đình, Âm nhạc, Giả tưởng',
        releaseYear: 2017,
        director: 'Lee Unkrich, Adrian Molina',
        actors: 'Anthony Gonzalez, Gael García Bernal, Benjamin Bratt, Alanna Ubach',
        trailer: 'https://www.youtube.com/embed/Rvr68u6k5sI?si=T0zw-gzJ5v6GQFeo&rel=0&modestbranding=1',
        type: "cartoons",
    },
    {
        id: 'spider-verse',
        title: 'Spider Man: Across the Spider-Verse',
        poster: './images/cartoons/spider-man.png',
        description: 'Khi du hành qua các vũ trụ song song, Miles Morales gặp một nhóm Người Nhện mới gồm những anh hùng đến từ các chiều không gian khác nhau. Tuy nhiên, khi các anh hùng bất đồng về cách đối phó với một mối đe dọa mới, Miles thấy mình đứng trước một quyết định quan trọng.',
        rating: 9.0,
        duration: '140m',
        quality: 'HD/4K',
        age_restriction: '13+',
        genre: 'Hoạt hình, Hành động, Phiêu lưu, Khoa học viễn tưởng',
        releaseYear: 2023,
        director: 'Joaquim Dos Santos, Kemp Powers, Justin K. Thompson',
        actors: 'Shameik Moore, Hailee Steinfeld, Oscar Isaac, Jake Johnson, Issa Rae',
        trailer: 'https://www.youtube.com/embed/shW9i6k8cB0?si=BK-6jSOafqZanckv&rel=0&modestbranding=1',
        type: "cartoons",
    },
    {
        id: 'dragonball',
        title: 'Dragonball Super: Broly',
        poster: './images/cartoons/dragonball.png',
        description: 'Dragon Ball Super: Broly kể về cuộc đối đầu giữa Goku, Vegeta và Broly — một Saiyan bị lưu đày từ nhỏ, sở hữu sức mạnh khủng khiếp. Được Frieza đưa đến Trái Đất để trả thù, Broly dần mất kiểm soát trong trận chiến. Goku và Vegeta buộc phải hợp thể thành Gogeta để ngăn chặn anh. Cuối cùng, Broly được cứu và sống yên bình, còn Goku muốn làm bạn và tiếp tục rèn luyện cùng anh.',
        rating: 8.5,
        duration: '100m',
        quality: '4K',
        age_restriction: '13+',
        genre: 'Hành động, Phiêu lưu, Anime, Giả tưởng',
        releaseYear: 2018,
        director: 'Tatsuya Nagamine',
        actors: 'Sean Schemmel, Christopher Sabat, Vic Mignogna',
        trailer: 'https://www.youtube.com/embed/ot9rao8kHgM?si=d4D9cRltNxjszW1q&rel=0&modestbranding=1',
        type: "cartoons",
    },
    {
        id: 'weathering',
        title: 'Weathering with You',
        poster: './images/cartoons/weathering.jpg',
        description: 'Lấy bối cảnh vào thời tiết mưa bất thường, cậu học sinh trung học Hodaka Morishima bỏ trốn khỏi ngôi nhà nông thôn đầy rắc rối của mình đến Tokyo và kết bạn với một cô gái mồ côi có khả năng điều khiển thời tiết.',
        rating: 8.0,
        duration: '112m',
        quality: 'HD/4K',
        age_restriction: '13+',
        genre: 'Hoạt hình, Chính kịch, Giả tưởng, Lãng mạn',
        releaseYear: 2019,
        director: 'Makoto Shinkai',
        actors: 'Kotaro Daigo, Nana Mori, Yûki Kaji',
        trailer: 'https://www.youtube.com/embed/Q6iK6DjV_iE?si=DwVy_92iMMjzsXdE&rel=0&modestbranding=1',
        type: "cartoons",
    },
    {
        id: 'demonslayer',
        title: 'Demon Slayer',
        poster: './images/cartoons/demon-slayer.jpg',
        description: 'Sau khi gia đình bị sát hại dã man và em gái cậu biến thành quỷ, hành trình diệt quỷ của Tanjiro Kamado bắt đầu. Tanjiro và đồng đội bắt đầu một nhiệm vụ mới trên Tàu Mugen, trên con đường tuyệt vọng.',
        rating: 8.4,
        duration: '117m',
        quality: 'HD/4K',
        age_restriction: '13+',
        genre: 'Hành động, Phiêu lưu, Anime, Giả tưởng',
        releaseYear: 2020,
        director: 'Haruo Sotozaki',
        actors: 'Zach Aguilar, Abby Trott, Bryce Papenbrook',
        trailer: 'https://www.youtube.com/embed/ddFX_Qnnq7g?si=f5u9X6loEljrXJyY&rel=0&modestbranding=1',
        type: "cartoons",
    },

    // banner phim  ------------------------------------------------------------------------------
    {
        id: 'the-boys-season-4',
        title: 'The Boys: Season 4',
        poster: './images/series/the-boys-season-4.png',
        banner_image: './images/banners/theboys_banner.jpg',
        description: 'Thế giới đang đứng bên bờ vực. Victoria Neuman hiện đang tiến rất gần đến vị trí Phó Tổng thống Mỹ và nằm dưới sự kiểm soát của Homelander - kẻ ngày càng củng cố quyền lực của mình. Trong khi Butcher chỉ còn vài tháng để sống, mất luôn cả vị trí lãnh đạo trong nhóm The Boys và niềm tin của đồng đội. Dù vậy, Butcher và nhóm vẫn buộc phải hợp tác một lần nữa để cứu lấy thế giới trước khi quá muộn.',
        rating: 9.0,
        duration: '60m',
        quality: 'HD/4K',
        age_restriction: '18+',
        genre: 'Hành động, Phiêu lưu, Chính trị, Bạo lực, Hài đen, Giật gân, Châm biếm xã hội',
        releaseYear: 2024,
        director: 'Eric Kripke, Frederick E.O. Toye, Shana Stein',
        actors: 'Karl Urban, Jack Quaid, Antony Starr, Erin Moriarty, Jessie T. Usher',
        trailer: 'https://www.youtube.com/embed/EzFXDvC-EwM?si=S2cfv0dLR83YSaPS&rel=0&modestbranding=1',
        type: "banners",
    },
    {
        id: 'shameless-season-5',
        title: 'Shameless: Season 5',
        poster: './images/series/shameless-ss5.png',
        banner_image: './images/banners/shameless.jpg',
        description: 'Fiona có một công việc ổn định và Lip đang học đại học, mang lại hy vọng cho gia đình Gallagher, nhưng rắc rối vẫn đeo bám họ. Frank cần một người hiến gan, Carl cố gắng giúp đỡ trong khi những người khác từ chối. Fiona lừa dối sếp của mình và bị bắt sau khi Liam dùng thuốc quá liều. Debbie tìm kiếm sự thay đổi, Ian trở về từ quân đội với nhiều thay đổi trong tâm lý, Veronica đang mang thai ba, quán bar thì đang thua lỗ, và Carol thì không cho cô phá thai.',
        rating: 9.0,
        duration: '60m',
        quality: 'HD',
        age_restriction: '18+',
        genre: 'Hài kịch, Drama',
        releaseYear: 2015,
        director: 'Christopher Chulack',
        actors: 'William H.Macy, Emmy Rossum, Jeremy Allen White, Cameron Monaghan, Ethan Cutkosky, Emma Kenney',
        trailer: 'https://www.youtube.com/embed/GWg54kkwC-M?si=-UbokIpHql0fYCmr&rel=0&modestbranding=1',
        type: "banners",
    },
    {
        id: 'venom-the-last-dance',
        title: 'Venom: The Last Dance',
        poster: './images/movies/venom.png',
        banner_image: './images/banners/venom.png',
        description: 'Eddie và Venom đang chạy trốn. Bị cả hai thế giới truy đuổi và lưới đang khép lại, bộ đôi này buộc phải đưa ra một quyết định tàn khốc sẽ hạ màn cho điệu nhảy cuối cùng của Venom và Eddie.',
        rating: 8.0,
        duration: '120m',
        quality: 'HD',
        age_restriction: '13+',
        genre: ' Siêu anh hùng, Hành động, Phiêu lưu, Khoa học viễn tưởng',
        releaseYear: 2024,
        director: 'Kelly Marcel',
        actors: 'Tom Hardy, Chiwetel Ejiofor, Juno Temple',
        trailer: 'https://www.youtube.com/embed/__2bjWbetsA?si=0-if8vWGz2cZcSBq&rel=0&modestbranding=1',
        type: "banners",
    },
    {
        id: 'guardian-o-t-g-3',
        title: 'Guardians of the Galaxy 3',
        poster: './images/movies/guardian.png',
        banner_image: './images/banners/guardian_banner.png',
        description: 'Vẫn chưa nguôi ngoai sau mất mát của Gamora, Peter Quill tập hợp đội của mình để bảo vệ vũ trụ và một người trong số họ. Một nhiệm vụ có thể dẫn đến sự kết thúc của nhóm Vệ binh nếu thất bại.',
        rating: 9.0,
        duration: '130m',
        quality: 'HD',
        age_restriction: '13+',
        genre: 'Hành động, Siêu anh hùng, Khoa học viễn tưởng, Phiêu lưu',
        releaseYear: 2023,
        director: 'James Gunn',
        actors: 'Chris Pratt, Chukwudi Iwuji, Bradley Cooper',
        trailer: 'https://www.youtube.com/embed/JqcncLPi9zw?si=ebUR-z4yMnA-OIaVY&rel=0&modestbranding=1',
        type: "banners",
    },
    {
        id: 'transformers-5',
        title: 'Transformers: The Last Knight',
        poster: './images/movies/transformer.jpg',
        banner_image: './images/banners/transformer_banner.jpg',
        description: 'Một mối đe dọa chết người từ quá khứ của Trái Đất trỗi dậy, và cuộc truy lùng một cổ vật bị thất lạc trở nên căng thẳng giữa Autobots và Decepticons, trong khi Optimus Prime chạm trán với người đã tạo ra mình ngoài không gian.',
        rating: 8.0,
        duration: '154m',
        quality: 'HD',
        age_restriction: '16+',
        genre: 'Khoa học viễn tưởng, Hành động & phiêu lưu',
        releaseYear: 2017,
        director: 'Michael Bay',
        actors: 'Mark Wahlberg, Anthony Hopkins, Josh Duhamel',
        trailer: 'https://www.youtube.com/embed/6Vtf0MszgP8?si=cM_UtGjEBEo6uE4S&rel=0&modestbranding=1',
        type: "banners",
    }

];

